name: Checkout Ingrid Actions
description: Checkouts Ingrid actions repository

inputs:
  path:
    description: The path where the actions should be checked out
    default: "ingrid-actions"

runs:
  using: "composite"
  steps:
    - name: Checkout Ingrid Actions Repo
      uses: actions/checkout@v3
      with:
        repository: shipwallet/github-actions
        token: ${{ env.GH_TOKEN }}
        path: ${{ inputs.path }}
